name: Build UwU ðŸ› 

on: [pull_request]

jobs:
  UnityAndArtifact:
    name: Building for unity (â—'â—¡'â—)
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: ./Desarrollo-3-2023/Library
          key: Library-${{ hashFiles('./Desarrollo-3-2023/Assets/**', './Desarrollo-3-2023/Packages/**', './Desarrollo-3-2023/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          projectPath: ././Desarrollo-3-2023/ProjectSettings
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows

          #Build name
          - name: Set Build name
          id: buildName
          run:
          sudo apt-get update
          echo "DATE=$(date + '%y%m%d')" >> $GITHUB_ENV

      # Upload build to github
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build